[package]
name = "vntyper"
version = "0.1.0"
authors = ["Do Duy <juchiast@gmail.com>"]

[dependencies]
rustc-serialize="0.3.19"
gtk = { git = "https://github.com/gtk-rs/gtk.git" }
lazy_static = "0.2.1"
